/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var Lofi:String = "event:/Music/Lofi";
}

class FmodSFX {
    public static inline var Die:String = "event:/SFX/Die";
    public static inline var Engine:String = "event:/SFX/Engine";
}
