/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
}

class FmodSFX {
    public static inline var Engine:String = "event:/SFX/Engine";
}
